name:  從 發佈 至 Github

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      MY_SECRET   : ${{secrets.commit_secret}}
      USER_NAME   : github-actions[bot]
      USER_EMAIL  : 41898282+github-actions[bot]@users.noreply.github.com
      PUBLISH_DIR : ./dotnetMVC/dotnetMVC/bin/publish
      PRJ_SLN     : ./dotnetMVC/dotnetMVC.sln
      COMMIT_STR  : "Bots Update : $(date \"+%Y/%m/%d %T\")"
    steps:
      - name: Get current date
        run: $COMMIT_STR 

      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          TAG_NAME: nightly-tag-${{ steps.date.outputs.date }}
          RELEASE_NAME: nightly-release-${{ steps.date.outputs.date }}
      - name: Test with input
        uses: actions/hello-world-docker-action@master
        with:
          who-to-greet: Mona-the-Octocat-${{ steps.date.outputs.date }}


