name:  從 發佈 至 Github

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      MY_SECRET   : ${{secrets.commit_secret}}
      USER_NAME   : github-actions[bot]
      USER_EMAIL  : 41898282+github-actions[bot]@users.noreply.github.com
      PUBLISH_DIR : ./dotnetMVC/dotnetMVC/bin/publish
      PRJ_SLN     : ./dotnetMVC/dotnetMVC.sln
      COMMIT_STR  : ::set-output name=date::$(date +'%Y-%m-%d')
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

