name:  從 發佈 至 Github

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      MY_SECRET   : ${{secrets.commit_secret}}
      USER_NAME   : github-actions[bot]
      USER_EMAIL  : 41898282+github-actions[bot]@users.noreply.github.com
      PUBLISH_DIR : ./dotnetMVC/dotnetMVC/bin/publish
      PRJ_SLN     : ./dotnetMVC/dotnetMVC.sln
      COMMIT_STR  : "Bots Update : $(date \"+%Y/%m/%d %T\")"
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x    
          
      - name: Restore NuGet Packages
        run: nuget restore ./MVC_CI_Demo/MVC_CI_Demo.sln 
          
      - name: Build Project
        run: dotnet build ./MVC_CI_Demo/MVC_CI_Demo.sln    

      - name: dotnet publish
        run: dotnet publish ./MVC_CI_Demo/MVC_CI_Demo.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp
  
      - name: echo
        run: echo ${{env.DOTNET_ROOT}}



