name: Test CI-Actions .NET


#----------------#
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#----------------#
jobs:
  build:
    #-------OS---------#
    runs-on: ubuntu-latest
    #runs-on: self-hosted#
    #-----------------#
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore NuGet Packages
      run: nuget restore ./MVC_CI_Demo/MVC_CI_Demo.sln 
        
    - name: Build Project
      run: dotnet build ./MVC_CI_Demo/MVC_CI_Demo.sln       
      
    - name: UnitTest Project
      run: dotnet test ./MVC_CI_Demo/MVC_CI_Demo.sln  
      
  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app
        
    - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item . C:/inetpub/DemoCD/dotnetcore-webapp -Recurse -Force
        iisreset /start
